/** Declaration file generated by dts-gen */

export function JSONiqLexer(): any;

export declare class XQLint {
	constructor(source: any, opts: any);

	getErrors(): any[];

	getWarnings(): any[];

	getAST(): any;
}

export function XQueryLexer(): any;

export function createStaticContext(): any;

